server.port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: api-a
          uri: lb://api-a
          predicates:
            - Path=/api/api-a/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: api-b
          uri: lb://api-b
          predicates:
            - Path=/api/api-b/**
          filters:
            - StripPrefix=1


management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always

