server.port: 9000

spring:
  application:
    name: gateway-service
  redis:
    host: 10.2.32.186
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: api-a
          uri: lb://api-a
          predicates:
            - Path=/api/api-a/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: api-b
          uri: lb://api-b
          predicates:
            - Path=/api/api-b/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback/default

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always

