spring:
  application:
    name: client-reactive-webclient-service

eureka:
  client:
    registryFetchIntervalSeconds: 1
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}}

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always