spring:
  application:
    name: client-resttemplate-service
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true

eureka:
  client:
    registryFetchIntervalSeconds: 1
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}}

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always