spring:
  application:
    name: client-resttemplate-service

eureka:
  client:
    registryFetchIntervalSeconds: 1

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always